local config = require("neotest-prove.config")

local DEFAULT_ROOT_FILES = { "cpanfile", "Makefile.PL", "Build.PL", "dist.ini", ".git" }

describe("config.merge", function()
  it("returns the defaults when given nil", function()
    local c = config.merge(nil)
    assert.equals("prove", c.prove_command)
    assert.equals("perl", c.perl_command)
    assert.is_false(c.include_xt)
    assert.same(DEFAULT_ROOT_FILES, c.root_files)
    assert.same({}, c.prove_args)
    assert.same({}, c.extra_filter_dirs)
  end)

  it("overrides a scalar option", function()
    local c = config.merge({ prove_command = { "carton", "exec", "prove" } })
    assert.same({ "carton", "exec", "prove" }, c.prove_command)
    assert.equals("perl", c.perl_command)
  end)

  it("overrides include_xt", function()
    assert.is_true(config.merge({ include_xt = true }).include_xt)
  end)

  it("replaces root_files wholesale rather than deep-merging", function()
    assert.same({ ".git" }, config.merge({ root_files = { ".git" } }).root_files)
  end)

  it("preserves unspecified defaults", function()
    local c = config.merge({ prove_args = { "-l" } })
    assert.same({ "-l" }, c.prove_args)
    assert.equals("perl", c.perl_command)
    assert.is_false(c.include_xt)
  end)

  it("raises on a non-table config", function()
    assert.has_error(function()
      config.merge("prove")
    end)
  end)

  it("does not mutate the defaults across calls", function()
    local first = config.merge({ root_files = { "only-this" } })
    assert.same({ "only-this" }, first.root_files)
    assert.same(DEFAULT_ROOT_FILES, config.merge(nil).root_files)
  end)

  it("raises on an unknown option name", function()
    assert.error_matches(function()
      config.merge({ prove_arg = { "-l" } })
    end, "unknown option")
  end)

  it("raises on an option of the wrong type", function()
    assert.error_matches(function()
      config.merge({ prove_args = "-l" })
    end, "prove_args")
    assert.error_matches(function()
      config.merge({ include_xt = "yes" })
    end, "include_xt")
  end)

  it("raises on a list option with a non-string element", function()
    assert.error_matches(function()
      config.merge({ prove_args = { "-l", 4 } })
    end, "prove_args.*list of strings")
    assert.error_matches(function()
      config.merge({ prove_command = { "carton", { "exec" } } })
    end, "prove_command.*list of strings")
    assert.error_matches(function()
      config.merge({ root_files = { name = ".git" } })
    end, "root_files.*list of strings")
  end)

  it("raises on a command that resolves to no arguments", function()
    assert.error_matches(function()
      config.merge({ prove_command = {} })
    end, "prove_command.*must not be empty")
    assert.error_matches(function()
      config.merge({ perl_command = "   " })
    end, "perl_command.*must not be empty")
  end)

  it("accepts an empty list", function()
    assert.same({}, config.merge({ root_files = {} }).root_files)
  end)
end)

describe("config.defaults", function()
  it("returns a fresh copy each time", function()
    local first = config.defaults()
    table.insert(first.root_files, "mutated")
    assert.same(DEFAULT_ROOT_FILES, config.defaults().root_files)
  end)
end)

describe("config.to_argv", function()
  it("splits a string on whitespace", function()
    assert.same({ "carton", "exec", "prove" }, config.to_argv("carton  exec\tprove"))
  end)

  it("copies a list without sharing it", function()
    local original = { "carton", "exec", "prove" }
    local argv = config.to_argv(original)
    assert.same(original, argv)
    argv[1] = "changed"
    assert.equals("carton", original[1])
  end)
end)
